services:
  - type: web
    name: work-history-chatbot-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    cors:
      allowOrigins:
        - https://your-netlify-app.netlify.app